server:
  port:

spring:
  profiles:
    include: secret

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:

logging:
  slack:
    webhook-uri:
  config:
